handlers:
  - sink: ext://sys.stdout
    level: ext://__main__.log_level
    enqueue: True
    backtrace: True
    diagnose: True
  - sink: fmt://{env://HOME}/Prj/github/barks-compleat-digital/barks-comic-building/logs/{ext://__main__.log_filename}
    level: "DEBUG"
    rotation: "10 MB"
    enqueue: True
    backtrace: True
    diagnose: True
